/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedActivityRouteImport } from './routes/_authenticated/activity'
import { Route as AuthenticatedAiChatRouteImport } from './routes/_authenticated/ai-chat'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmailGeneratorRouteImport } from './routes/_authenticated/email-generator'
import { Route as AuthenticatedMeetingSummarizerRouteImport } from './routes/_authenticated/meeting-summarizer'
import { Route as AuthenticatedResearchAssistantRouteImport } from './routes/_authenticated/research-assistant'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTaskPlannerRouteImport } from './routes/_authenticated/task-planner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivityRoute = AuthenticatedActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiChatRoute = AuthenticatedAiChatRouteImport.update({
  id: '/ai-chat',
  path: '/ai-chat',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailGeneratorRoute =
  AuthenticatedEmailGeneratorRouteImport.update({
    id: '/email-generator',
    path: '/email-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMeetingSummarizerRoute =
  AuthenticatedMeetingSummarizerRouteImport.update({
    id: '/meeting-summarizer',
    path: '/meeting-summarizer',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedResearchAssistantRoute =
  AuthenticatedResearchAssistantRouteImport.update({
    id: '/research-assistant',
    path: '/research-assistant',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTaskPlannerRoute =
  AuthenticatedTaskPlannerRouteImport.update({
    id: '/task-planner',
    path: '/task-planner',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-chat': typeof AuthenticatedAiChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-generator': typeof AuthenticatedEmailGeneratorRoute
  '/meeting-summarizer': typeof AuthenticatedMeetingSummarizerRoute
  '/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-planner': typeof AuthenticatedTaskPlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/activity': typeof AuthenticatedActivityRoute
  '/ai-chat': typeof AuthenticatedAiChatRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-generator': typeof AuthenticatedEmailGeneratorRoute
  '/meeting-summarizer': typeof AuthenticatedMeetingSummarizerRoute
  '/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/task-planner': typeof AuthenticatedTaskPlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/activity': typeof AuthenticatedActivityRoute
  '/_authenticated/ai-chat': typeof AuthenticatedAiChatRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-generator': typeof AuthenticatedEmailGeneratorRoute
  '/_authenticated/meeting-summarizer': typeof AuthenticatedMeetingSummarizerRoute
  '/_authenticated/research-assistant': typeof AuthenticatedResearchAssistantRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/task-planner': typeof AuthenticatedTaskPlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/activity'
    | '/ai-chat'
    | '/dashboard'
    | '/email-generator'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/settings'
    | '/task-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/activity'
    | '/ai-chat'
    | '/dashboard'
    | '/email-generator'
    | '/meeting-summarizer'
    | '/research-assistant'
    | '/settings'
    | '/task-planner'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/activity'
    | '/_authenticated/ai-chat'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-generator'
    | '/_authenticated/meeting-summarizer'
    | '/_authenticated/research-assistant'
    | '/_authenticated/settings'
    | '/_authenticated/task-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activity': {
      id: '/_authenticated/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof AuthenticatedActivityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-chat': {
      id: '/_authenticated/ai-chat'
      path: '/ai-chat'
      fullPath: '/ai-chat'
      preLoaderRoute: typeof AuthenticatedAiChatRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-generator': {
      id: '/_authenticated/email-generator'
      path: '/email-generator'
      fullPath: '/email-generator'
      preLoaderRoute: typeof AuthenticatedEmailGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/meeting-summarizer': {
      id: '/_authenticated/meeting-summarizer'
      path: '/meeting-summarizer'
      fullPath: '/meeting-summarizer'
      preLoaderRoute: typeof AuthenticatedMeetingSummarizerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/research-assistant': {
      id: '/_authenticated/research-assistant'
      path: '/research-assistant'
      fullPath: '/research-assistant'
      preLoaderRoute: typeof AuthenticatedResearchAssistantRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/task-planner': {
      id: '/_authenticated/task-planner'
      path: '/task-planner'
      fullPath: '/task-planner'
      preLoaderRoute: typeof AuthenticatedTaskPlannerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivityRoute: typeof AuthenticatedActivityRoute
  AuthenticatedAiChatRoute: typeof AuthenticatedAiChatRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailGeneratorRoute: typeof AuthenticatedEmailGeneratorRoute
  AuthenticatedMeetingSummarizerRoute: typeof AuthenticatedMeetingSummarizerRoute
  AuthenticatedResearchAssistantRoute: typeof AuthenticatedResearchAssistantRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTaskPlannerRoute: typeof AuthenticatedTaskPlannerRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivityRoute: AuthenticatedActivityRoute,
  AuthenticatedAiChatRoute: AuthenticatedAiChatRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailGeneratorRoute: AuthenticatedEmailGeneratorRoute,
  AuthenticatedMeetingSummarizerRoute: AuthenticatedMeetingSummarizerRoute,
  AuthenticatedResearchAssistantRoute: AuthenticatedResearchAssistantRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTaskPlannerRoute: AuthenticatedTaskPlannerRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
